language: php

php:
    - '7.1'
    - '7.2'
    - 'hhvm'
    
env:
    global:
        - 'DB_CONNECTION=mysql'
        - 'DB_HOST=localhost'
        - 'DB_DATABASE=codeuser'
        - 'DB_USERNAME=travis'
    
before_install:
    - composer selfupdate
    
install:
    - composer install

before_script:
    - mysql -utravis -e "create database codeuser;"

script:
    - vendor/bin/phpunit